import {
  FiTarget,
  FiTrendingUp,
  FiDollarSign,
  FiAward,
  FiMenu,
  FiX,
  FiInstagram,
  FiLinkedin,
  FiStar,
  FiCheck,
  FiChevronDown,
  FiArrowRight,
  FiUsers,
  FiBookOpen,
  FiHeart,
  FiClock,
  FiLayers,
  FiUser,
  FiCamera,
  FiBriefcase,
  FiMonitor,
  FiVideo,
  FiBarChart2,
  FiPenTool,
  FiHash,
  FiZap,
  FiPlay,
} from "react-icons/fi";
import { FaInstagram, FaTiktok, FaFacebook, FaLinkedin, FaTelegram, FaWhatsapp } from "react-icons/fa6";
import { BsCameraReels } from "react-icons/bs";
import { IconType } from "react-icons";

const iconMap: Record<string, IconType> = {
  FiTarget,
  FiTrendingUp,
  FiDollarSign,
  FiAward,
  FiMenu,
  FiX,
  FiInstagram,
  FiLinkedin,
  FiStar,
  FiCheck,
  FiChevronDown,
  FiArrowRight,
  FiUsers,
  FiBookOpen,
  FiHeart,
  FiClock,
  FiLayers,
  FiUser,
  FiCamera,
  FiBriefcase,
  FiMonitor,
  FiVideo,
  FiBarChart2,
  FiPenTool,
  FiHash,
  FiZap,
  FiPlay,
  FaInstagram,
  FaTiktok,
  FaFacebook,
  FaLinkedin,
  FaTelegram,
  FaWhatsapp,
  FaReels: BsCameraReels,
  BsCameraReels,
};

export function getIcon(name: string): IconType {
  return iconMap[name] ?? FiTarget;
}

export {
  FiTarget,
  FiTrendingUp,
  FiDollarSign,
  FiAward,
  FiMenu,
  FiX,
  FiInstagram,
  FiLinkedin,
  FiStar,
  FiCheck,
  FiChevronDown,
  FiArrowRight,
};
